name: "Continuous Integration"
on: [push, pull_request]

jobs:
  tests:
    name: "CI"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v1, php-cs-fixer, phpstan, phpunit:8.5.8

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test PHPUnit
        env:
          SCRUTINIZER_API_ACCESS_TOKEN: ${{ secrets.SCRUTINIZER_API_ACCESS_TOKEN }}
        run:
          - phpunit --coverage-clover=coverage.clover
          - wget https://scrutinizer-ci.com/ocular.phar
          - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_API_ACCESS_TOKEN" --format=php-clover coverage.clover

      - name: Test PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --no-ansi

      - name: Test PHPStan
        run: phpstan analyse
